name: Sample Book App Workflow

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest #self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Logging in to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - uses: ./.github/actions/build
  deploy-dev:
    runs-on: ubuntu-latest #self-hosted
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with: 
          environment: 'dev'
  test-dev:
    runs-on: ubuntu-latest #self-hosted
    needs: [deploy-dev]
    steps:
      - run: echo "Tests triggered on DEV env..."
  deploy-stg:
    runs-on: ubuntu-latest #self-hosted
    needs: [test-dev]
      steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with: 
          environment: 'stg'
  test-stg:
    runs-on: ubuntu-latest #self-hosted
    needs: [deploy-stg]
    steps:
      - run: echo "Tests triggered on STG env..."
  deploy-prd:
    runs-on: ubuntu-latest #self-hosted
    needs: [test-stg]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with: 
          environment: 'prd'
  test-prd:
    runs-on: ubuntu-latest #self-hosted
    needs: [deploy-prd]
    steps:
      - run: echo "Tests triggered on PRD env..."
